FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Retail Webservice API

Polls is a simple API allowing consumers to view polls and vote in them.

## Quote Collection [/quote]

### Application Quote [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
        "proposalNo": "BG375060",
        "amount":"6500",
        "term": "60",
        "purpose": "BTL",
        "joint": false,
        "receiveMarketing": true,
        "sourceCode": "BG",
        "instance": "britishgas",
        "loanType": "U",
        "clientIP": "172.17.0.106",
        "appStatus": "NEW",
        "appSubStatus": "NONE",            
        "thirdPartyReference":"46968",
        "applicants": [{
                        "joint": "P",
                        "title": "Ms",
                        "firstname": "Ewart",
                        "middlename": "",
                        "surname": "Dunnage",
                        "dateOfBirth": "06/01/1980",
                        "gender": "M",
                        "maritalStatus": "S",
                        "dependents": "1",
                        "dependentsList": "2",
                        "email": "ittestingteam@freedom-finance.com",
                        "homePhone": "01611111111",
                        "workPhone": "",
                        "mobilePhone": "07234567890",
                        "residentialStatus": "M",
                        "nationality": "BRITISH",
                        "ukResident": "true",
                        "ukCitizen": "true",
                        "over25": "true",
                        "applicant_addresses": [{
                                        "address": {
                                                        "houseNo": "37",
                                                        "street": "Monopoly Close",
                                                        "posttown": "test town",
                                                        "county": "",
                                                        "postcode": "X98HJ",
                                                        "country": "United Kingdom",
                                                        "years": "5",
                                                        "months": "7",
                                                        "equifax_key": "",
                                                        "locality": ""
                                        },
                                        "type": "C",
                                        "rank": "1"
                        }, {
                                "address": {
                                    "houseNo": "37",
                                    "street": "Monopoly Close",
                                    "posttown": "test town",
                                    "county": "",
                                    "postcode": "X98HJ",
                                    "country": "United Kingdom",
                                    "years": 20,
                                    "months": 7,
                                    "equifax_key": ""
                            },
                            "type": "P",
                            "rank": "2"
                        }],
                        "employments": [{
                            "type": "E",
                            "years": "20",
                            "months": "8",
                            "grossPayMonthly": "",
                            "netPay": "",
                            "selfEmployed": "false",
                            "fullContract": "N",
                            "rank": "1",
                            "netPayMonthly": 8500,
                            "grossPay": "100000",
                            "address": {
                                            "houseNo": "20",
                                            "street": "Test Street",
                                            "posttown": "Town Town",
                                            "county": "CHESHIRE",
                                            "postcode": "BA133BN",
                                            "country": "UNITED KINGDOM",
                                            "years": "6",
                                            "months": "0"
                            }
                        }],
                        
                        "otherIncomes": [{
                                        "description": "SES",
                                        "income": 693,
                                        "rank": "1"                          
                        }, {
                                        "description": "TOT",
                                        "income": 239,
                                        "rank": 2
                        }],           
                        
                        "proof": [{
                                        "type": "PPT",
                                        "reference": "123456789"
                        }],
                                        
                        "bankDetails": [{
                                        "accountName": "Mr E Dunnage",
                                        "accountNumber": "11111111",
                                        "accountBranch": "TEST BRANCH",
                                        "years": 15,
                                        "months": 0,
                                        "bankName": "LloydsTSB",
                                        "sortcode": "301122",
                                        "directDebitDate": "29/08/2016",
                                        "street": "Test Street",
                                        "locality": "Test Locality",
                                        "posttown": "Test Town",
                                        "county": "CHESHIRE",
                                        "postcode": ""
        }]
        
        }],           
        "onsData": [{
                        "appjEmployment": "H",
                        "appjIncome": 2340.20
        }],

        "initialCode": "001",
        "initialStatus": "",
        "cashDeposit": "756.90"
        }

+ Response 200 (text/html;charset=utf-8)

            {

            "submissions": {
                "actualApr": 29.9,
                "dateCreated": "2016-10-18T13:51:25Z",
                "id": 2084,
                "lenderCode": "hcb",
                "lenderName": "Test Finance",
                "lenderReference": "1891",
                "notes": "",
                "submissionStatus": "ACCEPT",
                "loanTerm": "24",
                "monthlyRepayment": "37.87",
                "totalRepayable": "908.88",
                "totalCostOfCredit": "208.88"
            }

            }
            
+ Response 201 (text/html;charset=utf-8)

            {
              "submissions": {
                "submissionStatus": "Declined"
              }
            }